name: Image vuln scan

on:
  workflow_dispatch:
  schedule:
    - cron: "22 7 * * 0"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan - Full
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/xdev-software/mockserver-neolight:latest'

      - name: Scan - Relevant
        id: scan_relevant
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/xdev-software/mockserver-neolight:latest'
          exit-code: 1
          severity: 'HIGH,CRITICAL'
          output: reported.txt

      - name: Find already existing issue
        id: find-issue
        if: ${{ failure() && steps.scan_relevant.conclusion == 'failure' }}
        run: |
          echo "number=$(gh issue list -l 'bug' -l 'automated' -L 1 -S 'in:title \"Link Checker Report\"' -s 'open' --json 'number' --jq '.[].number')" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Close issue if everything is fine
        if: ${{ failure() && steps.scan_relevant.conclusion == 'failure' && steps.find-issue.outputs.number != '' }}
        run: gh issue close -r 'not planned' ${{ steps.find-issue.outputs.number }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create Issue From File
        if: ${{ failure() && steps.scan_relevant.conclusion == 'failure' }}
        uses: peter-evans/create-issue-from-file@v5
        with:
          issue-number: ${{ steps.find-issue.outputs.number }}
          title: Trivy Vulnerability Report
          content-filepath: ./reported.txt
          labels: bug, automated
