name: Vulnerability scan

on:
  workflow_dispatch:
  schedule:
    - cron: "22 7 * * 0"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan - Full
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/xdev-software/mockserver-neolight:latest'

      - name: Scan - Critical
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/xdev-software/mockserver-neolight:latest'
          exit-code: 1
          severity: 'HIGH,CRITICAL'
